### ISSUE TITLE
RuntimeError: Expected object of scalar type Long but got scalar type Float for argument

### ISSUE THREAD

**Issue by naoki7090624** [raywzy/ICT#24]
Hi, thank you for sharing code.

I want to run training code on grayscale images, but i got following error.
```
# Mask is 12022, # Image is 12022
# Mask is 12022, # Image is 0
Warnning: There is no trained model found. An initialized model will be used.
Warnning: There is no previous optimizer found. An initialized optimizer will be used.
Resume from Epoch 0
Traceback (most recent call last):
  File "main.py", line 139, in <module>
    mp.spawn(main_worker, nprocs=opts.gpus, args=(opts,))
  File "/home/naoki/.pyenv/versions/3.8.6/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/naoki/.pyenv/versions/3.8.6/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/home/naoki/.pyenv/versions/3.8.6/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/naoki/.pyenv/versions/3.8.6/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/home/naoki/ICT/Transformer/main.py", line 73, in main_worker
    trainer.train(loaded_ckpt)
  File "/home/naoki/ICT/Transformer/DDP_trainer.py", line 203, in train
    run_epoch('train')
  File "/home/naoki/ICT/Transformer/DDP_trainer.py", line 139, in run_epoch
    logits, loss = model(x, y)
  File "/home/naoki/.pyenv/versions/3.8.6/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/naoki/.pyenv/versions/3.8.6/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 799, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/naoki/.pyenv/versions/3.8.6/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/naoki/ICT/Transformer/models/model.py", line 254, in forward
    loss = F.cross_entropy(logits.view(-1, logits.size(-1)), targets.view(-1))
  File "/home/naoki/.pyenv/versions/3.8.6/lib/python3.8/site-packages/torch/nn/functional.py", line 2824, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
RuntimeError: Expected object of scalar type Long but got scalar type Float for argument #2 'target' in call to _thnn_nll_loss_forward
```

I checked the size and data type before cross entropy loss.
'''
logits: torch.Size([12, 1024, 512]), torch.float32
targets: torch.Size([12, 1024]), torch.float32
'''

Could you give me how to solve this problem.
Thank you in advance.

**Comment by naoki7090624** [comment]
Solved!!

**Comment by zhangshilong2000** [comment]
您好，这个问题是怎么解决的？
