### ISSUE TITLE
ProcessExitedException: process 0 terminated with signal SIGKILL

### ISSUE THREAD

**Issue by CyrilCsy** [raywzy/ICT#38]
Has anyone encountered this error，torch.multiprocessing.spawn.ProcessExitedException: process 0 terminated with signal SIGKILL. I am wondering a solution.

**Comment by wzy46775852** [comment]
hi, I have the same problem as you, can you solve it, I use a GPU for training

**Comment by AnNnnH3** [comment]
The same problem too,have you solved it?

**Comment by zhangshilong2000** [comment]
你好解决了吗？

**Comment by lipenghuai** [comment]
python main.py --nodes 1 --gpus 4 --batch_size 16 --node_rank 0 --AMP
# Mask is 22648, # Image is 22648
# Mask is 22648, # Image is 22648
# Mask is 22648, # Image is 22648
# Mask is 22648, # Image is 22648
# Mask is 9232, # Image is 9232
# Mask is 9232, # Image is 9232
# Mask is 9232, # Image is 9232
# Mask is 9232, # Image is 9232
Traceback (most recent call last):
  File "main.py", line 140, in <module>
    mp.spawn(main_worker, nprocs=opts.gpus, args=(opts,))
  File "/home/dell/anaconda3/envs/lipict/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 199, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/dell/anaconda3/envs/lipict/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 157, in start_processes
    while not context.join():
  File "/home/dell/anaconda3/envs/lipict/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 107, in join
    (error_index, name)
Exception: process 3 terminated with signal SIGKILL

**Comment by Seventeen1711** [comment]
The same problem too,have you solved it?

**Comment by lipenghuai** [comment]
> 你好解决了吗？

已解决（没有认真读论文导致的），但是目前只能单卡训练。
